sudo: required
dist: bionic
language: cpp
os:
  - linux
arch:
  - amd64
compiler:
  - gcc
addons:
   apt:
      packages:
      - zlib1g-dev
      - libbz2-dev
      - libsnappy-dev
      - curl
      - libgflags-dev
      - mingw-w64
      - libcurl4-openssl-dev
      - libssl-dev
      - uuid-dev
      - libpulse-dev

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

services:
  - docker

jobs:
  include:
    - stage: Build
      script: docker run -v $TRAVIS_BUILD_DIR:/opt/rocksdb-cloud/src -w /opt/rocksdb-cloud/src -u $UID -e V=1 -e USE_AWS=1 -e USE_KAFKA=1 -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm rockset/rocksdb_cloud_runtime:test /bin/bash -c "make -j4 cloud_manifest_test db_cloud_test && aws --recursive s3 cp $TRAVIS_BUILD_DIR/.cache s3://rockset.dbcloudtest.1000/$TRAVIS_BUILD_ID/.cache"
    - stage: Test
      script: docker run -v $TRAVIS_BUILD_DIR:/opt/rocksdb-cloud/src -w /opt/rocksdb-cloud/src -u $UID -e V=1 -e USE_AWS=1 -e USE_KAFKA=1 -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm rockset/rocksdb_cloud_runtime:test /bin/bash -c "aws --recursive s3 cp s3://rockset.dbcloudtest.1000/$TRAVIS_BUILD_ID/.cache $TRAVIS_BUILD_DIR/.cache && make -j4 cloud_manifest_test && ./cloud_manifest_test"
    - script: docker run -v $TRAVIS_BUILD_DIR:/opt/rocksdb-cloud/src -w /opt/rocksdb-cloud/src -u $UID -e V=1 -e USE_AWS=1 -e USE_KAFKA=1 -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm rockset/rocksdb_cloud_runtime:test /bin/bash -c "aws --recursive s3 cp s3://rockset.dbcloudtest.1000/$TRAVIS_BUILD_ID/.cache $TRAVIS_BUILD_DIR/.cache && make -j4 db_cloud_test && ./db_cloud_test --gtest_filter=-CloudTest.KeepLocalLogKafka"
    #   script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test --gtest_filter=-DBTest.MergeTestTime:DBTest.UnsupportedManualSync:DBTest.ApproximateSizes*:DBTest.HiddenValuesAreRemoved:DBTest.UnremovableSingleDelete:DBTest.OverlapInLevel0:MultiThreaded/MultiThreadedDBTest*:DBTest.SingleDeleteFlush:DBTest.GetLevel0Ordering:DBTest.GetPicksCorrectFile
    # - script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test --gtest_filter=DBTest.SingleDeleteFlush:DBTest.GetLevel0Ordering:DBTest.GetPicksCorrectFile
    # - script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test --gtest_filter=DBTest.HiddenValuesAreRemoved
    # - script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test --gtest_filter=DBTest.UnremovableSingleDelete
    # - script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test --gtest_filter=MultiThreaded/MultiThreadedDBTest*
    # - script: OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_test2 db_basic_test env_basic_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test2 && LD_LIBRARY_PATH=/usr/local/lib ./db_basic_test --gtest_filter=-DBBasicTest.CompactBetweenSnapshots && LD_LIBRARY_PATH=/usr/local/lib ./env_basic_test
    # - script: build_tools/spinup_kafka.sh && sleep 10 && OPT=-DTRAVIS V=1 USE_AWS=1 USE_KAFKA=1 make -j4 db_cloud_test cloud_manifest_test && LD_LIBRARY_PATH=/usr/local/lib ./db_cloud_test && LD_LIBRARY_PATH=/usr/local/lib ./cloud_manifest_test


before_script:
  # Increase the maximum number of open file descriptors, since some tests use
  # more FDs than the default limit.
  docker pull rockset/rocksdb_cloud_runtime:test

notifications:
  slack:
    rooms:
      - rockset-io:4q1pfQSzMd3UgSR18Yu23quQ#rocksdb-cloud-ci
    on_success: always
    on_failure: always
